[package]
name = "lappi"
version = "0.1.0"
authors = ["Andrew Dirksen <andrew@dirksen.com>"]
edition = "2018"

[dependencies]
u256 = "0.1.0"
futures = "0.1.25"
lightning-invoice = "0.2.0"
bitcoin_hashes = "0.3.1"
secp256k1 = "0.12.2"
rand = "0.6.5"
