version: '2'
services:

    # btc is an image of bitcoin node which used as base image for btcd and
    # btccli. The environment variables default values determined on stage of
    # container start within starting script.
    btc:
      image: btcd
      build:
        context: btcd/
      volumes:
        - lappi_persist_btcd_rpc:/rpc
        - lappi_persist_btcd_data:/root/.btcd/data
        - lappi_persist_btcd_logs:/root/.btcd/logs
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK=mainnet

    btcd:
        extends: btc
        container_name: btcd
        environment:
          - DEBUG
          - MINING_ADDRESS
        entrypoint: ["./start-btcd.sh"]

    lnd:
        ports:
          - "10009:10009"
        image: lnd
        build:
          context: lnd
          dockerfile: Dockerfile
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK=mainnet
          - CHAIN
          - DEBUG
        volumes:
          - lappi_persist_btcd_rpc:/rpc
          - lappi_persist_lnd_dir:/root/.lnd
        entrypoint: ["./start-lnd.sh"]

    lnd_btc:
      extends: lnd
      container_name: lnd_btc
      links:
          - "btcd:blockchain"

volumes:
  # These volumes point to hardcoded paths. This will need to be fixed before prod.
  
  # shared volume is needed to store the btcd rpc certificates for use from lnd
  lappi_persist_btcd_rpc:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Volumes/btcchain/persist/btcd_rpc

  # Btc chain is stored here
  lappi_persist_btcd_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Volumes/btcchain/persist/btcd_data

  # Btc logs are stored here
  lappi_persist_btcd_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Volumes/btcchain/persist/btcd_logs

  # Lnd config lives here
  lappi_persist_lnd_dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Volumes/btcchain/persist/lnd_dir
