version: '2'
services:
  bitcoind:
    image: bitcoind
    container_name: bitcoind
    ports:
      - "8333:8333"
      - "28335:28335"
      - "28336:28336"
    build:
      context: bitcoind
    volumes:
      - lappi_persist_bitcoind:/root/.bitcoin

  lnd:
    ports:
      - "10009:10009"
    image: lnd
    container_name: lnd
    build:
      context: lnd
    volumes:
      - lappi_persist_bitcoind:/root/.bitcoin
      - lappi_persist_lnd:/root/.lnd
    entrypoint: ["./start-lnd.sh"]
    links:
      - "bitcoind:blockchain"


volumes:
  # These volumes point to hardcoded paths. This will need to be fixed before prod.
  
  # shared volume is needed to store the btcd rpc certificates for use from lnd
  lappi_persist_lnd:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Volumes/btcchain/persist/lnd
      
  # bicoind Btc chain is stored here
  lappi_persist_bitcoind:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Volumes/btcchain/persist/bitcoind
